services:
  # Backend API Service
  - type: web
    name: belvcrysta-api
    env: python
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: MONGO_URI
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
